version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - govet
    - ineffassign
    - modernize
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - predeclared
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    nolintlint:
      require-explanation: true
      require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
